apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rbln-npu-feature-discovery
  namespace: node-feature-discovery
  labels:
    app.kubernetes.io/name: rbln-npu-feature-discovery
    app.kubernetes.io/version: v0.1.4
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rbln-npu-feature-discovery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rbln-npu-feature-discovery
        app.kubernetes.io/version: v0.1.4
    spec:
      containers:
        - image: rebellions/rbln-npu-feature-discovery:v0.1.4
          name: rbln-npu-feature-discovery
          command: ["/usr/local/bin/rbln-npu-feature-discovery"]
          volumeMounts:
            - name: output-dir
              mountPath: "/etc/kubernetes/node-feature-discovery/features.d"
            - name: host-sys
              mountPath: "/sys"
          securityContext:
            privileged: true
      hostNetwork: true
      terminationGracePeriodSeconds: 0
      volumes:
        - name: output-dir
          hostPath:
            path: "/etc/kubernetes/node-feature-discovery/features.d"
        - name: host-sys
          hostPath:
            path: "/sys"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            # this is the label generated by NFD with default configuration, targeting rebellions vendor id (1eff)
            - matchExpressions:
              - key: feature.node.kubernetes.io/pci-1200_1eff.present
                operator: In
                values:
                - "true"
            - matchExpressions:
              - key: feature.node.kubernetes.io/pci-1eff.present
                operator: In
                values:
                - "true"
      tolerations:
        - key: ""
          operator: Exists
          effect: NoSchedule
        - key: ""
          operator: Exists
          effect: NoExecute
