// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: rbln_services.proto

package rblnservicespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	// indicates valid data in message
	Status_SUCCEED Status = 0
	// indicates invalid data in message
	Status_FAILED Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "SUCCEED",
		1: "FAILED",
	}
	Status_value = map[string]int32{
		"SUCCEED": 0,
		"FAILED":  1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_rbln_services_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_rbln_services_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{0}
}

type EventType int32

const (
	// event does snot require response(daemon to kernel response)
	EventType_NO_RESPONSE EventType = 0
	// event requires response(daemon to kernel response)
	EventType_RESPONSE_REQUIRED EventType = 1
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "NO_RESPONSE",
		1: "RESPONSE_REQUIRED",
	}
	EventType_value = map[string]int32{
		"NO_RESPONSE":       0,
		"RESPONSE_REQUIRED": 1,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_rbln_services_proto_enumTypes[1].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_rbln_services_proto_enumTypes[1]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{1}
}

type EventSource int32

const (
	// event occured from single device hard reset
	EventSource_SIGNLE_HARD_RESET EventSource = 0
	// event occured from rsd device hard reset
	EventSource_RSD_HARD_RESET EventSource = 1
	// event occured from TDR
	EventSource_TDR_EVENT EventSource = 2
	// event occured from CP event
	EventSource_CP_EVENT EventSource = 3
)

// Enum value maps for EventSource.
var (
	EventSource_name = map[int32]string{
		0: "SIGNLE_HARD_RESET",
		1: "RSD_HARD_RESET",
		2: "TDR_EVENT",
		3: "CP_EVENT",
	}
	EventSource_value = map[string]int32{
		"SIGNLE_HARD_RESET": 0,
		"RSD_HARD_RESET":    1,
		"TDR_EVENT":         2,
		"CP_EVENT":          3,
	}
)

func (x EventSource) Enum() *EventSource {
	p := new(EventSource)
	*p = x
	return p
}

func (x EventSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventSource) Descriptor() protoreflect.EnumDescriptor {
	return file_rbln_services_proto_enumTypes[2].Descriptor()
}

func (EventSource) Type() protoreflect.EnumType {
	return &file_rbln_services_proto_enumTypes[2]
}

func (x EventSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventSource.Descriptor instead.
func (EventSource) EnumDescriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{2}
}

type StatusMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// just wrapper message for enum type data
	ErrStatus     Status `protobuf:"varint,1,opt,name=err_status,json=errStatus,proto3,enum=rblnservices.Status" json:"err_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusMsg) Reset() {
	*x = StatusMsg{}
	mi := &file_rbln_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusMsg) ProtoMessage() {}

func (x *StatusMsg) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusMsg.ProtoReflect.Descriptor instead.
func (*StatusMsg) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{0}
}

func (x *StatusMsg) GetErrStatus() Status {
	if x != nil {
		return x.ErrStatus
	}
	return Status_SUCCEED
}

type Device struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device name (e.g. 'rbln0')
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// device id (e.g. '1120', '1121')
	DevId string `protobuf:"bytes,2,opt,name=dev_id,json=devId,proto3" json:"dev_id,omitempty"`
	// device uuid (00000000-0000-0000-0000-000000000000 format)
	Uuid          string `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_rbln_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{1}
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetDevId() string {
	if x != nil {
		return x.DevId
	}
	return ""
}

func (x *Device) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ClockInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CP clock information (Mhz)
	CpClock int32 `protobuf:"varint,1,opt,name=cp_clock,json=cpClock,proto3" json:"cp_clock,omitempty"`
	// DNC1 clock information (Mhz)
	Dc1Clock int32 `protobuf:"varint,2,opt,name=dc1_clock,json=dc1Clock,proto3" json:"dc1_clock,omitempty"`
	// DNC2 clock information (Mhz)
	Dc2Clock int32 `protobuf:"varint,3,opt,name=dc2_clock,json=dc2Clock,proto3" json:"dc2_clock,omitempty"`
	// Bus clock information (Mhz)
	BusClock int32 `protobuf:"varint,4,opt,name=bus_clock,json=busClock,proto3" json:"bus_clock,omitempty"`
	// SHM clock information (Mhz)
	ShmClock int32 `protobuf:"varint,5,opt,name=shm_clock,json=shmClock,proto3" json:"shm_clock,omitempty"`
	// error status
	ErrStatus     Status `protobuf:"varint,6,opt,name=err_status,json=errStatus,proto3,enum=rblnservices.Status" json:"err_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClockInfo) Reset() {
	*x = ClockInfo{}
	mi := &file_rbln_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockInfo) ProtoMessage() {}

func (x *ClockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockInfo.ProtoReflect.Descriptor instead.
func (*ClockInfo) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{2}
}

func (x *ClockInfo) GetCpClock() int32 {
	if x != nil {
		return x.CpClock
	}
	return 0
}

func (x *ClockInfo) GetDc1Clock() int32 {
	if x != nil {
		return x.Dc1Clock
	}
	return 0
}

func (x *ClockInfo) GetDc2Clock() int32 {
	if x != nil {
		return x.Dc2Clock
	}
	return 0
}

func (x *ClockInfo) GetBusClock() int32 {
	if x != nil {
		return x.BusClock
	}
	return 0
}

func (x *ClockInfo) GetShmClock() int32 {
	if x != nil {
		return x.ShmClock
	}
	return 0
}

func (x *ClockInfo) GetErrStatus() Status {
	if x != nil {
		return x.ErrStatus
	}
	return Status_SUCCEED
}

type VersionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Firmware version.
	FwVersion string `protobuf:"bytes,1,opt,name=fw_version,json=fwVersion,proto3" json:"fw_version,omitempty"`
	// Kernel driver version.
	DrvVersion string `protobuf:"bytes,2,opt,name=drv_version,json=drvVersion,proto3" json:"drv_version,omitempty"`
	// SMC version.
	SmcVersion string `protobuf:"bytes,3,opt,name=smc_version,json=smcVersion,proto3" json:"smc_version,omitempty"`
	// error status
	ErrStatus     Status `protobuf:"varint,4,opt,name=err_status,json=errStatus,proto3,enum=rblnservices.Status" json:"err_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionInfo) Reset() {
	*x = VersionInfo{}
	mi := &file_rbln_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionInfo) ProtoMessage() {}

func (x *VersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionInfo.ProtoReflect.Descriptor instead.
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{3}
}

func (x *VersionInfo) GetFwVersion() string {
	if x != nil {
		return x.FwVersion
	}
	return ""
}

func (x *VersionInfo) GetDrvVersion() string {
	if x != nil {
		return x.DrvVersion
	}
	return ""
}

func (x *VersionInfo) GetSmcVersion() string {
	if x != nil {
		return x.SmcVersion
	}
	return ""
}

func (x *VersionInfo) GetErrStatus() Status {
	if x != nil {
		return x.ErrStatus
	}
	return Status_SUCCEED
}

type HWInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// temperature in celsius unit.
	Temperature float32 `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// hardware watt.
	Watt float32 `protobuf:"fixed32,2,opt,name=watt,proto3" json:"watt,omitempty"`
	// error status
	ErrStatus     Status `protobuf:"varint,3,opt,name=err_status,json=errStatus,proto3,enum=rblnservices.Status" json:"err_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HWInfo) Reset() {
	*x = HWInfo{}
	mi := &file_rbln_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HWInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HWInfo) ProtoMessage() {}

func (x *HWInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HWInfo.ProtoReflect.Descriptor instead.
func (*HWInfo) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{4}
}

func (x *HWInfo) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *HWInfo) GetWatt() float32 {
	if x != nil {
		return x.Watt
	}
	return 0
}

func (x *HWInfo) GetErrStatus() Status {
	if x != nil {
		return x.ErrStatus
	}
	return Status_SUCCEED
}

type MemoryInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device total memory (GB unit)
	TotalMem float32 `protobuf:"fixed32,1,opt,name=total_mem,json=totalMem,proto3" json:"total_mem,omitempty"`
	// device memory in use (GB unit)
	UsedMem float32 `protobuf:"fixed32,2,opt,name=used_mem,json=usedMem,proto3" json:"used_mem,omitempty"`
	// error status
	ErrStatus     Status `protobuf:"varint,3,opt,name=err_status,json=errStatus,proto3,enum=rblnservices.Status" json:"err_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryInfo) Reset() {
	*x = MemoryInfo{}
	mi := &file_rbln_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInfo) ProtoMessage() {}

func (x *MemoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInfo.ProtoReflect.Descriptor instead.
func (*MemoryInfo) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{5}
}

func (x *MemoryInfo) GetTotalMem() float32 {
	if x != nil {
		return x.TotalMem
	}
	return 0
}

func (x *MemoryInfo) GetUsedMem() float32 {
	if x != nil {
		return x.UsedMem
	}
	return 0
}

func (x *MemoryInfo) GetErrStatus() Status {
	if x != nil {
		return x.ErrStatus
	}
	return Status_SUCCEED
}

type UtilInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// utilization(percent) of device processing unit
	Utilization float32 `protobuf:"fixed32,1,opt,name=utilization,proto3" json:"utilization,omitempty"`
	// error status
	ErrStatus     Status `protobuf:"varint,2,opt,name=err_status,json=errStatus,proto3,enum=rblnservices.Status" json:"err_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UtilInfo) Reset() {
	*x = UtilInfo{}
	mi := &file_rbln_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtilInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtilInfo) ProtoMessage() {}

func (x *UtilInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtilInfo.ProtoReflect.Descriptor instead.
func (*UtilInfo) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{6}
}

func (x *UtilInfo) GetUtilization() float32 {
	if x != nil {
		return x.Utilization
	}
	return 0
}

func (x *UtilInfo) GetErrStatus() Status {
	if x != nil {
		return x.ErrStatus
	}
	return Status_SUCCEED
}

type EventInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device name
	DevName string `protobuf:"bytes,1,opt,name=dev_name,json=devName,proto3" json:"dev_name,omitempty"`
	// event type
	EventType EventType `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=rblnservices.EventType" json:"event_type,omitempty"`
	// event value
	Value EventSource `protobuf:"varint,3,opt,name=value,proto3,enum=rblnservices.EventSource" json:"value,omitempty"`
	// sub event value
	SubValue int32 `protobuf:"varint,4,opt,name=sub_value,json=subValue,proto3" json:"sub_value,omitempty"`
	// event trigger time (uptime)
	KernelTime float64 `protobuf:"fixed64,5,opt,name=kernel_time,json=kernelTime,proto3" json:"kernel_time,omitempty"`
	// UTC time with host time zone.
	UtcTime       string `protobuf:"bytes,6,opt,name=utc_time,json=utcTime,proto3" json:"utc_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventInfo) Reset() {
	*x = EventInfo{}
	mi := &file_rbln_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventInfo) ProtoMessage() {}

func (x *EventInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventInfo.ProtoReflect.Descriptor instead.
func (*EventInfo) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{7}
}

func (x *EventInfo) GetDevName() string {
	if x != nil {
		return x.DevName
	}
	return ""
}

func (x *EventInfo) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_NO_RESPONSE
}

func (x *EventInfo) GetValue() EventSource {
	if x != nil {
		return x.Value
	}
	return EventSource_SIGNLE_HARD_RESET
}

func (x *EventInfo) GetSubValue() int32 {
	if x != nil {
		return x.SubValue
	}
	return 0
}

func (x *EventInfo) GetKernelTime() float64 {
	if x != nil {
		return x.KernelTime
	}
	return 0
}

func (x *EventInfo) GetUtcTime() string {
	if x != nil {
		return x.UtcTime
	}
	return ""
}

type DeviceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// device uuid
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// device total memory (GB unit)
	TotalMem float32 `protobuf:"fixed32,3,opt,name=total_mem,json=totalMem,proto3" json:"total_mem,omitempty"`
	// device memory in use (GB unit)
	UsedMem float32 `protobuf:"fixed32,4,opt,name=used_mem,json=usedMem,proto3" json:"used_mem,omitempty"`
	// temperature in celsius unit.
	Temperature float32 `protobuf:"fixed32,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// hardware watt currently consumed
	Watt float32 `protobuf:"fixed32,6,opt,name=watt,proto3" json:"watt,omitempty"`
	// firmware version
	FwVersion string `protobuf:"bytes,7,opt,name=fw_version,json=fwVersion,proto3" json:"fw_version,omitempty"`
	// kernel driver version
	DrvVersion string `protobuf:"bytes,8,opt,name=drv_version,json=drvVersion,proto3" json:"drv_version,omitempty"`
	// device utilization
	Utilization float32 `protobuf:"fixed32,9,opt,name=utilization,proto3" json:"utilization,omitempty"`
	// error status
	ErrStatus     Status `protobuf:"varint,10,opt,name=err_status,json=errStatus,proto3,enum=rblnservices.Status" json:"err_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_rbln_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DeviceInfo) GetTotalMem() float32 {
	if x != nil {
		return x.TotalMem
	}
	return 0
}

func (x *DeviceInfo) GetUsedMem() float32 {
	if x != nil {
		return x.UsedMem
	}
	return 0
}

func (x *DeviceInfo) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *DeviceInfo) GetWatt() float32 {
	if x != nil {
		return x.Watt
	}
	return 0
}

func (x *DeviceInfo) GetFwVersion() string {
	if x != nil {
		return x.FwVersion
	}
	return ""
}

func (x *DeviceInfo) GetDrvVersion() string {
	if x != nil {
		return x.DrvVersion
	}
	return ""
}

func (x *DeviceInfo) GetUtilization() float32 {
	if x != nil {
		return x.Utilization
	}
	return 0
}

func (x *DeviceInfo) GetErrStatus() Status {
	if x != nil {
		return x.ErrStatus
	}
	return Status_SUCCEED
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_rbln_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{9}
}

var File_rbln_services_proto protoreflect.FileDescriptor

const file_rbln_services_proto_rawDesc = "" +
	"\n" +
	"\x13rbln_services.proto\x12\frblnservices\"@\n" +
	"\tStatusMsg\x123\n" +
	"\n" +
	"err_status\x18\x01 \x01(\x0e2\x14.rblnservices.StatusR\terrStatus\"G\n" +
	"\x06Device\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06dev_id\x18\x02 \x01(\tR\x05devId\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\"\xcf\x01\n" +
	"\tClockInfo\x12\x19\n" +
	"\bcp_clock\x18\x01 \x01(\x05R\acpClock\x12\x1b\n" +
	"\tdc1_clock\x18\x02 \x01(\x05R\bdc1Clock\x12\x1b\n" +
	"\tdc2_clock\x18\x03 \x01(\x05R\bdc2Clock\x12\x1b\n" +
	"\tbus_clock\x18\x04 \x01(\x05R\bbusClock\x12\x1b\n" +
	"\tshm_clock\x18\x05 \x01(\x05R\bshmClock\x123\n" +
	"\n" +
	"err_status\x18\x06 \x01(\x0e2\x14.rblnservices.StatusR\terrStatus\"\xa3\x01\n" +
	"\vVersionInfo\x12\x1d\n" +
	"\n" +
	"fw_version\x18\x01 \x01(\tR\tfwVersion\x12\x1f\n" +
	"\vdrv_version\x18\x02 \x01(\tR\n" +
	"drvVersion\x12\x1f\n" +
	"\vsmc_version\x18\x03 \x01(\tR\n" +
	"smcVersion\x123\n" +
	"\n" +
	"err_status\x18\x04 \x01(\x0e2\x14.rblnservices.StatusR\terrStatus\"s\n" +
	"\x06HWInfo\x12 \n" +
	"\vtemperature\x18\x01 \x01(\x02R\vtemperature\x12\x12\n" +
	"\x04watt\x18\x02 \x01(\x02R\x04watt\x123\n" +
	"\n" +
	"err_status\x18\x03 \x01(\x0e2\x14.rblnservices.StatusR\terrStatus\"y\n" +
	"\n" +
	"MemoryInfo\x12\x1b\n" +
	"\ttotal_mem\x18\x01 \x01(\x02R\btotalMem\x12\x19\n" +
	"\bused_mem\x18\x02 \x01(\x02R\ausedMem\x123\n" +
	"\n" +
	"err_status\x18\x03 \x01(\x0e2\x14.rblnservices.StatusR\terrStatus\"a\n" +
	"\bUtilInfo\x12 \n" +
	"\vutilization\x18\x01 \x01(\x02R\vutilization\x123\n" +
	"\n" +
	"err_status\x18\x02 \x01(\x0e2\x14.rblnservices.StatusR\terrStatus\"\xe8\x01\n" +
	"\tEventInfo\x12\x19\n" +
	"\bdev_name\x18\x01 \x01(\tR\adevName\x126\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2\x17.rblnservices.EventTypeR\teventType\x12/\n" +
	"\x05value\x18\x03 \x01(\x0e2\x19.rblnservices.EventSourceR\x05value\x12\x1b\n" +
	"\tsub_value\x18\x04 \x01(\x05R\bsubValue\x12\x1f\n" +
	"\vkernel_time\x18\x05 \x01(\x01R\n" +
	"kernelTime\x12\x19\n" +
	"\butc_time\x18\x06 \x01(\tR\autcTime\"\xb9\x02\n" +
	"\n" +
	"DeviceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1b\n" +
	"\ttotal_mem\x18\x03 \x01(\x02R\btotalMem\x12\x19\n" +
	"\bused_mem\x18\x04 \x01(\x02R\ausedMem\x12 \n" +
	"\vtemperature\x18\x05 \x01(\x02R\vtemperature\x12\x12\n" +
	"\x04watt\x18\x06 \x01(\x02R\x04watt\x12\x1d\n" +
	"\n" +
	"fw_version\x18\a \x01(\tR\tfwVersion\x12\x1f\n" +
	"\vdrv_version\x18\b \x01(\tR\n" +
	"drvVersion\x12 \n" +
	"\vutilization\x18\t \x01(\x02R\vutilization\x123\n" +
	"\n" +
	"err_status\x18\n" +
	" \x01(\x0e2\x14.rblnservices.StatusR\terrStatus\"\a\n" +
	"\x05Empty*!\n" +
	"\x06Status\x12\v\n" +
	"\aSUCCEED\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01*3\n" +
	"\tEventType\x12\x0f\n" +
	"\vNO_RESPONSE\x10\x00\x12\x15\n" +
	"\x11RESPONSE_REQUIRED\x10\x01*U\n" +
	"\vEventSource\x12\x15\n" +
	"\x11SIGNLE_HARD_RESET\x10\x00\x12\x12\n" +
	"\x0eRSD_HARD_RESET\x10\x01\x12\r\n" +
	"\tTDR_EVENT\x10\x02\x12\f\n" +
	"\bCP_EVENT\x10\x032\xe3\x05\n" +
	"\fRBLNServices\x12>\n" +
	"\rgetDeviceList\x12\x13.rblnservices.Empty\x1a\x14.rblnservices.Device\"\x000\x01\x12I\n" +
	"\x18getServiceableDeviceList\x12\x13.rblnservices.Empty\x1a\x14.rblnservices.Device\"\x000\x01\x12>\n" +
	"\vresetDevice\x12\x14.rblnservices.Device\x1a\x17.rblnservices.StatusMsg\"\x00\x12@\n" +
	"\x0eresetAllDevice\x12\x13.rblnservices.Empty\x1a\x17.rblnservices.StatusMsg\"\x00\x12?\n" +
	"\n" +
	"getVersion\x12\x14.rblnservices.Device\x1a\x19.rblnservices.VersionInfo\"\x00\x129\n" +
	"\tgetHWInfo\x12\x14.rblnservices.Device\x1a\x14.rblnservices.HWInfo\"\x00\x12A\n" +
	"\rgetMemoryInfo\x12\x14.rblnservices.Device\x1a\x18.rblnservices.MemoryInfo\"\x00\x12?\n" +
	"\fgetClockInfo\x12\x14.rblnservices.Device\x1a\x17.rblnservices.ClockInfo\"\x00\x12A\n" +
	"\fgetEventInfo\x12\x14.rblnservices.Device\x1a\x17.rblnservices.EventInfo\"\x000\x01\x12A\n" +
	"\fgetTotalInfo\x12\x13.rblnservices.Empty\x1a\x18.rblnservices.DeviceInfo\"\x000\x01\x12@\n" +
	"\x0egetUtilization\x12\x14.rblnservices.Device\x1a\x16.rblnservices.UtilInfo\"\x00BCZAgithub.com/rebellions-sw/rbln-metrics-exporter/pkg/rblnservicespbb\x06proto3"

var (
	file_rbln_services_proto_rawDescOnce sync.Once
	file_rbln_services_proto_rawDescData []byte
)

func file_rbln_services_proto_rawDescGZIP() []byte {
	file_rbln_services_proto_rawDescOnce.Do(func() {
		file_rbln_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rbln_services_proto_rawDesc), len(file_rbln_services_proto_rawDesc)))
	})
	return file_rbln_services_proto_rawDescData
}

var file_rbln_services_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_rbln_services_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rbln_services_proto_goTypes = []any{
	(Status)(0),         // 0: rblnservices.Status
	(EventType)(0),      // 1: rblnservices.EventType
	(EventSource)(0),    // 2: rblnservices.EventSource
	(*StatusMsg)(nil),   // 3: rblnservices.StatusMsg
	(*Device)(nil),      // 4: rblnservices.Device
	(*ClockInfo)(nil),   // 5: rblnservices.ClockInfo
	(*VersionInfo)(nil), // 6: rblnservices.VersionInfo
	(*HWInfo)(nil),      // 7: rblnservices.HWInfo
	(*MemoryInfo)(nil),  // 8: rblnservices.MemoryInfo
	(*UtilInfo)(nil),    // 9: rblnservices.UtilInfo
	(*EventInfo)(nil),   // 10: rblnservices.EventInfo
	(*DeviceInfo)(nil),  // 11: rblnservices.DeviceInfo
	(*Empty)(nil),       // 12: rblnservices.Empty
}
var file_rbln_services_proto_depIdxs = []int32{
	0,  // 0: rblnservices.StatusMsg.err_status:type_name -> rblnservices.Status
	0,  // 1: rblnservices.ClockInfo.err_status:type_name -> rblnservices.Status
	0,  // 2: rblnservices.VersionInfo.err_status:type_name -> rblnservices.Status
	0,  // 3: rblnservices.HWInfo.err_status:type_name -> rblnservices.Status
	0,  // 4: rblnservices.MemoryInfo.err_status:type_name -> rblnservices.Status
	0,  // 5: rblnservices.UtilInfo.err_status:type_name -> rblnservices.Status
	1,  // 6: rblnservices.EventInfo.event_type:type_name -> rblnservices.EventType
	2,  // 7: rblnservices.EventInfo.value:type_name -> rblnservices.EventSource
	0,  // 8: rblnservices.DeviceInfo.err_status:type_name -> rblnservices.Status
	12, // 9: rblnservices.RBLNServices.getDeviceList:input_type -> rblnservices.Empty
	12, // 10: rblnservices.RBLNServices.getServiceableDeviceList:input_type -> rblnservices.Empty
	4,  // 11: rblnservices.RBLNServices.resetDevice:input_type -> rblnservices.Device
	12, // 12: rblnservices.RBLNServices.resetAllDevice:input_type -> rblnservices.Empty
	4,  // 13: rblnservices.RBLNServices.getVersion:input_type -> rblnservices.Device
	4,  // 14: rblnservices.RBLNServices.getHWInfo:input_type -> rblnservices.Device
	4,  // 15: rblnservices.RBLNServices.getMemoryInfo:input_type -> rblnservices.Device
	4,  // 16: rblnservices.RBLNServices.getClockInfo:input_type -> rblnservices.Device
	4,  // 17: rblnservices.RBLNServices.getEventInfo:input_type -> rblnservices.Device
	12, // 18: rblnservices.RBLNServices.getTotalInfo:input_type -> rblnservices.Empty
	4,  // 19: rblnservices.RBLNServices.getUtilization:input_type -> rblnservices.Device
	4,  // 20: rblnservices.RBLNServices.getDeviceList:output_type -> rblnservices.Device
	4,  // 21: rblnservices.RBLNServices.getServiceableDeviceList:output_type -> rblnservices.Device
	3,  // 22: rblnservices.RBLNServices.resetDevice:output_type -> rblnservices.StatusMsg
	3,  // 23: rblnservices.RBLNServices.resetAllDevice:output_type -> rblnservices.StatusMsg
	6,  // 24: rblnservices.RBLNServices.getVersion:output_type -> rblnservices.VersionInfo
	7,  // 25: rblnservices.RBLNServices.getHWInfo:output_type -> rblnservices.HWInfo
	8,  // 26: rblnservices.RBLNServices.getMemoryInfo:output_type -> rblnservices.MemoryInfo
	5,  // 27: rblnservices.RBLNServices.getClockInfo:output_type -> rblnservices.ClockInfo
	10, // 28: rblnservices.RBLNServices.getEventInfo:output_type -> rblnservices.EventInfo
	11, // 29: rblnservices.RBLNServices.getTotalInfo:output_type -> rblnservices.DeviceInfo
	9,  // 30: rblnservices.RBLNServices.getUtilization:output_type -> rblnservices.UtilInfo
	20, // [20:31] is the sub-list for method output_type
	9,  // [9:20] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_rbln_services_proto_init() }
func file_rbln_services_proto_init() {
	if File_rbln_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rbln_services_proto_rawDesc), len(file_rbln_services_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rbln_services_proto_goTypes,
		DependencyIndexes: file_rbln_services_proto_depIdxs,
		EnumInfos:         file_rbln_services_proto_enumTypes,
		MessageInfos:      file_rbln_services_proto_msgTypes,
	}.Build()
	File_rbln_services_proto = out.File
	file_rbln_services_proto_goTypes = nil
	file_rbln_services_proto_depIdxs = nil
}
